### ISSUE TITLE
Limited to int ?

### ISSUE THREAD

**Issue by mpgn** [ntns/goitertools#2]
Everything is limited to int `iterable []int`, but Python can also handle string

Example : 

```
combinations('ABCD', 2) --> AB AC AD BC BD CD
```

Is there a simple way to convert this to handle string ?

**Comment by ntns** [comment]
This package is just someting I did when I was learning Go and should not be used on anything serious. Regarding your question, yes it is limited to int and the only way to handle string would be to rewrite all functions to use string instead of int.

My advice is to search godoc.org for a package that suits your needs better.

PS - I will delete this repository in a few days to prevent confusion to anyone finding it.

**Comment by mpgn** [comment]
ok :)
